name = "ONNX"
uuid = "d0dd6a25-fac6-55c0-abf7-829e0c774d20"
version = "0.2.7"

[deps]
EnumX = "4e289a0a-7415-4d19-859d-a7e5c4648b56"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
ProtoBuf = "3349acd9-ac6a-5e09-bcdb-63829b23a429"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Umlaut = "92992a2b-8ce5-4a9c-bb9d-58be9a7dc841"

[compat]
EnumX = "1"
NNlib = "0.8, 0.9"
ProtoBuf = "1.0"
StaticArrays = "1"
Umlaut = "0.4, 0.5, 0.6, 0.7"
julia = "1.6"
