name = "ONNX"
uuid = "d0dd6a25-fac6-55c0-abf7-829e0c774d20"
version = "0.2.0"

[deps]
ProtoBuf = "3349acd9-ac6a-5e09-bcdb-63829b23a429"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
ProtoBuf = "= 0.9.0"
julia = "1"
